### ISSUE TITLE
Proposition Status DRAFT as External Link only

### ISSUE THREAD

**Issue by GamesGamble** [edemocracy/ekklesia-portal#28]
We can use the Proposition Status DRAFT as external link to discourse only, and so we still support rewriting the proposition content, abstract and motivation. Should have a Time Limit related to the policy in which the Proposition Status (automatically?) switches to Proposition Status Submitted and extracts the content, abstract and motivation from discourse via [discourse-ekklesia plugin](https://github.com/Piratenpartei/discourse-ekklesia) into the ekklesia portal.

**Comment by dpausp** [comment]
this is realized in the draft workflow like: submit a draft, content is posted to discourse, submitting brings back the content from discourse to the portal. This shouldn't happen automatically but we can implement are notification to the submitter if drafts are getting old :)
